networks:
  AI_Dev:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

volumes:
  nginx-html:
    driver: local
    # Temporarily disabled bind mount for troubleshooting
    # driver_opts:
    #   type: none
    #   device: /mnt/c/Users/Owner/dev/Dev_docker_stack/dev_stack/config/html
    #   o: bind
  # Supabase volumes for future integration
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./db_volumes/db
      o: bind
  functions-data:
    driver: local
    driver_opts:
      type: none
      device: ./db_volumes/functions
      o: bind
  api-data:
    driver: local
    driver_opts:
      type: none
      device: ./db_volumes/api
      o: bind
  storage-data:
    driver: local
    driver_opts:
      type: none
      device: ./db_volumes/storage
      o: bind
  logs-data:
    driver: local
    driver_opts:
      type: none
      device: ./db_volumes/logs
      o: bind

services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    environment:
      - TZ=America/Los_Angeles # Change this to your timezone
      - TUNNEL_TOKEN=${TUNNEL_ENV_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - AI_Dev # Use the same network as the other services
# cloudflared tunnel is typically port 7844

  nginx:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - AI_Dev
    ports:
      - "127.0.0.1:8082:80"
    volumes:
      - nginx-html:/usr/share/nginx/html    # Removed :ro for testing
      - ./config/nginx:/etc/nginx:ro
      
    # Add logging volume if needed
    # - ./logs/nginx:/var/log/nginx

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    networks:
      - AI_Dev
    ports:
      - "9090:9090"
    environment:
      - TZ=America/Los_Angeles

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - AI_Dev
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Los_Angeles

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    ports:
      - "8081:8080"
    networks:
      - AI_Dev
    volumes:
      - ./db_volumes/open-webui:/data    # Store settings externally

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    networks:
      - AI_Dev
    ports:
      - "5678:5678"
    volumes:
      - ./db_volumes/n8n:/home/node/.n8n
    environment:
      - TZ=America/Los_Angeles
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin

  flowise:
    image: flowiseai/flowise:latest
    restart: unless-stopped
    networks:
      - AI_Dev
    ports:
      - "3003:3000"
    volumes:
      - ./db_volumes/flowise:/root/.flowise
    environment:
      - TZ=America/Los_Angeles 