# API Keys
SERPER_API_KEY: ""
OPENAI_API_KEY: ""

# LLM Settings
DEFAULT_SERVER: "ollama"
DEFAULT_MODEL: "llama3.1"
DEFAULT_TEMPERATURE: 0
DEFAULT_RECURSION_LIMIT: 40
DEFAULT_STOP_TOKEN: "<|end_of_text|>" 